#!/usr/bin/env python
# coding: utf-8

# In[1]:


fraudulent_job_phrases = [
    "Work from home",
    "High salary/pay",
    "No experience required",
    "Immediate start",
    "Unlimited earning potential",
    "No background check",
    "Upfront payment",
    "Financial/banking information",
    "Pyramid scheme/multi-level marketing",
    "Grammatical/spelling errors",
    "No background check required",
    "Immediate hiring",
    "Easy work, high pay",
    "No qualifications needed",
    "Unlimited income potential",
    "Get rich quick",
    "Work at your own pace",
    "No experience necessary",
    "Start earning today",
    "Limited positions available",
    "No interview required",
    "Guaranteed earnings",
    "Earn money from home",
    "No investment required",
    "Fast cash opportunity",
    "Earn thousands weekly",
    "Make money online",
    "No selling required",
    "Instant payment",
    "No startup costs",
    "No boss, work independently",
    "Quick and easy training",
    "Work on your schedule",
    "Immediate income opportunity",
    "High-paying part-time job",
    "Work from anywhere",
    "Flexible working hours",
    "Earn big money fast",
    "Join our winning team",
    "Home-based business opportunity",
    "Easy money from home",
    "Financial freedom",
    "Earn while you sleep",
    "No experience, no problem",
    "Limited-time offer",
    "Join our exclusive program",
    "Instant cash rewards",
    "Earn passive income",
    "Work with reputable company",
    "No risk, high reward",
    "No background check necessary",
    "Earn money on autopilot",
    "Financial independence",
    "Be your own boss",
    "Get paid to travel",
    "Work from anywhere in the world",
    "Earn money effortlessly",
    "Join our elite team",
    "Earn money with little effort",
    "No previous experience needed",
    "Earn money quickly",
    "Immediate cash rewards",
    "High earnings potential",
    "No qualifications necessary",
    "Make money in your spare time",
    "Earn cash today",
    "Limited spots available",
    "No upfront fees",
    "Start making money now",
    "Work from the comfort of your home",
    "Earn big with minimal effort",
    "No investment, high returns",
    "Earn cash from home",
    "Get paid instantly",
    "No degree required",
    "Unlimited earning opportunities",
    "Work from your smartphone",
    "Earn money instantly",
    "No strings attached",
    "Limited-time opportunity",
    "No special skills needed",
    "Earn money on your own terms",
    "Join our lucrative program",
    "Make money with ease",
    "No experience, no problem",
    "Earn money effortlessly",
    "Fast and easy cash",
    "Earn money with no effort",
    "High-paying remote job",
    "Earn money without leaving home",
    "Start earning immediately",
    "Work from anywhere, anytime",
    "Earn money with ease",
    "Earn money with just a few clicks",
    "Get paid for your opinions",
    "No risk, high rewards",
    "Earn cash with no investment",
    "Work and earn at your own pace",
    "No selling required, just earning",
    "Earn money without lifting a finger",
    "Make money with no effort",
    "Get paid to do easy tasks",
    "No experience necessary, just earnings",
    "Earn money without any hassles",
    "High-paying work-from-home job",
    "Earn money with minimal effort",
    "Get paid for simple tasks",
    "Earn cash without leaving your home"
]


# In[ ]:




